# Generated by Django 5.2.7 on 2025-10-15 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangarinorg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='college',
        ),
        migrations.RemoveField(
            model_name='program',
            name='college',
        ),
        migrations.RemoveField(
            model_name='orgmember',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='orgmember',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hangarinorg.basemodel')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
            bases=('hangarinorg.basemodel',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hangarinorg.basemodel')),
                ('content', models.TextField()),
            ],
            bases=('hangarinorg.basemodel',),
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hangarinorg.basemodel')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priorities',
            },
            bases=('hangarinorg.basemodel',),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hangarinorg.basemodel')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='pending', max_length=50)),
            ],
            bases=('hangarinorg.basemodel',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hangarinorg.basemodel')),
                ('Title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='pending', max_length=50)),
                ('task_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangarinorg.category')),
                ('task_priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangarinorg.priority')),
            ],
            bases=('hangarinorg.basemodel',),
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrgMember',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='subtask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangarinorg.task'),
        ),
        migrations.AddField(
            model_name='note',
            name='related_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangarinorg.task'),
        ),
    ]
