# Generated by Django 5.2.7 on 2025-10-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangarinorg', '0002_alter_subtask_status_alter_subtask_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
